CREATE TABLE one_big_table (
    game_key INTEGER,
    pitch_number INTEGER,
    inning INTEGER,
    inning_topbot VARCHAR,
    outs_when_up INTEGER,
    pitch_type VARCHAR,
    release_speed FLOAT,
    release_spin_rate FLOAT,
    pfx_x FLOAT,
    pfx_z FLOAT,
    plate_x FLOAT,
    plate_z FLOAT,
    zone INTEGER,
    type VARCHAR,
    events VARCHAR,
    launch_speed FLOAT,
    launch_angle FLOAT,
    hit_distance_sc FLOAT,
    pitcher_key INTEGER,
    batter_key INTEGER,
    count_key INTEGER,
    PRIMARY KEY (game_key, pitch_number)
);