table one_big_table {
  pitch_type varchar
  game_date date
  release_speed float
  release_pos_x float
  release_pos_z float
  player_name varchar
  batter integer
  pitcher integer
  events varchar
  description varchar
  spin_dir float
  spin_rate_deprecated float
  break_angle_deprecated float
  break_length_deprecated float
  zone integer
  des varchar
  game_type varchar
  stand varchar
  p_throws varchar
  home_team varchar
  away_team varchar
  type varchar
  hit_location float
  bb_type varchar
  balls integer
  strikes integer
  game_year integer
  pfx_x float
  pfx_z float
  plate_x float
  plate_z float
  on_3b integer
  on_2b integer
  on_1b integer
  outs_when_up integer
  inning integer
  inning_topbot varchar
  hc_x float
  hc_y float
  tfs_deprecated varchar
  tfs_zulu_deprecated varchar
  umpire varchar
  sv_id varchar
  vx0 float
  vy0 float
  vz0 float
  ax float
  ay float
  az float
  sz_top float
  sz_bot float
  hit_distance_sc float
  launch_speed float
  launch_angle float
  effective_speed float
  release_spin_rate float
  release_extension float
  game_pk integer
  fielder_2 integer
  fielder_3 integer
  fielder_4 integer
  fielder_5 integer
  fielder_6 integer
  fielder_7 integer
  fielder_8 integer
  fielder_9 integer
  release_pos_y float
  estimated_ba_using_speedangle float
  estimated_woba_using_speedangle float
  woba_value float
  woba_denom float
  babip_value float
  iso_value float
  launch_speed_angle integer
  at_bat_number integer
  pitch_number integer [pk]
  pitch_name varchar
  home_score integer
  away_score integer
  bat_score integer
  fld_score integer
  post_away_score integer
  post_home_score integer
  post_bat_score integer
  post_fld_score integer
  if_fielding_alignment varchar
  of_fielding_alignment varchar
  spin_axis float
  delta_home_win_exp float
  delta_run_exp float
  bat_speed float
  swing_length float
  estimated_slg_using_speedangle float
  delta_pitcher_run_exp float
  hyper_speed float
  home_score_diff integer
  bat_score_diff integer
  home_win_exp float
  bat_win_exp float
  age_pit_legacy float
  age_bat_legacy float
  age_pit float
  age_bat float
  n_thruorder_pitcher integer
  n_priorpa_thisgame_player_at_bat integer
  pitcher_days_since_prev_game integer
  batter_days_since_prev_game integer
  pitcher_days_until_next_game integer
  batter_days_until_next_game integer
  api_break_z_with_gravity float
  api_break_x_arm float
  api_break_x_batter_in float
  arm_angle float
  attack_angle float
  attack_direction float
  swing_path_tilt float
  intercept_ball_minus_batter_pos_x_inches float
  intercept_ball_minus_batter_pos_y_inches float
  game_date_game date
  season integer
  game_type_game varchar
  home_team_game varchar
  away_team_game varchar
  stadium varchar
  day_of_week varchar
  weather_temp integer
  weather_condition varchar
  total_pitches integer
  pitcher_full_name varchar
  pitcher_first_name varchar
  pitcher_last_name varchar
  pitcher_birth_date date
  pitcher_birth_city varchar
  pitcher_birth_country varchar
  pitcher_height varchar
  pitcher_weight integer
  pitcher_bat_side varchar
  pitcher_pitch_hand varchar
  pitcher_primary_position varchar
  pitcher_mlb_debut_date date
  batter_full_name varchar
  batter_first_name varchar
  batter_last_name varchar
  batter_birth_date date
  batter_birth_city varchar
  batter_birth_country varchar
  batter_height varchar
  batter_weight integer
  batter_bat_side varchar
  batter_pitch_hand varchar
  batter_primary_position varchar
  batter_mlb_debut_date date
  count_display varchar
  count_category varchar
  velocity_tier varchar
  is_strike boolean
  is_ball boolean
  is_in_play boolean
  is_swing_and_miss boolean
  is_hit boolean
  is_home_run boolean
  is_strikeout boolean
  is_walk boolean
}